name: $(BuildDefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

variables:
  mavenPomFile : 'pom.xml'
  funcAppName: 'ARMState20191214083323'
  resourceGroupName: 'vidarfunctest'
  location: 'Westeurope'
  #serviceConnection: ''

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    zipAfterPublish: true
    publishWebProjects: false
    projects:
      src/ARMState.csproj

- task: PowerShell@2
  displayName: Check if infrastcuture should be updated
  inputs:
    targetType: 'filePath' # Optional. Options: filePath, inline
    filePath: deployment/check-rgstatus.ps1
    arguments: '-key $(funcAppName)dev -filesToHash $(Build.SourcesDirectory)/deployment/azuredeploy.json,$(Build.SourcesDirectory)/deployment/azuredeploy.parameters.json'
    errorActionPreference: 'stop' # Optional. Options: stop, continue, silentlyContinue
    failOnStderr: true # Optional
    pwsh: true # Optional

- task: AzureResourceGroupDeployment@2
  displayName: Provision Azure infrastructure
  condition: and(succeeded(), ne(variables['noprovision'], 'true'))
  inputs:
    action: Create Or Update Resource Group
    location: $(location)
    azureSubscription: $(serviceConnection)
    resourceGroupName: '$(resourceGroupName)'
    templateLocation: Linked artifact
    csmFile: 'azuredeploy.json'
    csmParametersFile: 'azuredeploy.parameters.json'

- task: PowerShell@2
  displayName: Save state of infrastructure configuration
  condition: and(succeeded(), ne(variables['noprovision'], 'true'))
  inputs:
    targetType: 'filePath' # Optional. Options: filePath, inline
    filePath: deployment/update-rgstatus.ps1
    arguments: '-key $(funcAppName)dev -filesToHash $(Build.SourcesDirectory)/deployment/azuredeploy.json,$(Build.SourcesDirectory)/deployment/azuredeploy.parameters.json'
    errorActionPreference: 'stop' # Optional. Options: stop, continue, silentlyContinue
    failOnStderr: true # Optional
    pwsh: true # Optional

- task: AzureFunctionApp@1
  displayName: Deploy function app
  inputs:
    azureSubscription: $(serviceConnection)
    appType: functionApp
    appName: $(funcAppName)
    package: '$(Build.ArtifactStagingDirectory)/$(funcAppName)$(Build.BuildId).zip'
